---
name: ci

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

jobs:
  ci:
    name: ${{ matrix.solution }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solution:
        - Watchmin.Server
        - Watchmin.Client
        - Watchmin.Modules

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore
      working-directory: ${{ matrix.solution }}

    - name: Dotnet build
      run: dotnet build
      working-directory: ${{ matrix.solution }}

    - name: Dotnet test
      run: dotnet test
      working-directory: ${{ matrix.solution }}
