---
name: lint

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["**"]

jobs:
  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Run editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@v2

  yamllint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Run yamllint
      uses: karancode/yamllint-github-action@v2.1.1
      with:
        yamllint_config_filepath: .yamllint.yaml
