---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags: ["**"]

jobs:
  release:
    name: ${{ matrix.solution.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solution:
        - name: Watchmin.Modules

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet nuget source
      run: >-
        dotnet nuget add source
        --name "github"
        --username "BeeHiveJava"
        --password "${{ secrets.GITHUB_TOKEN }}"
        --store-password-in-clear-text
        "https://nuget.pkg.github.com/BeeHiveJava/index.json"
      working-directory: ${{ matrix.solution.name }}

    - name: Dotnet restore
      run: dotnet restore
      working-directory: ${{ matrix.solution.name }}

    - name: Dotnet build
      run: dotnet build --no-restore --configuration "Release"
      working-directory: ${{ matrix.solution.name }}

    - name: Dotnet pack
      run: dotnet pack --no-build --configuration "Release" /p:Version="${{ github.ref_name }}"
      working-directory: ${{ matrix.solution.name }}

    - name: Dotnet push
      run: >-
        dotnet nuget push
        --source "github"
        --api-key "${{ secrets.GITHUB_TOKEN }}"
        "**/*.nupkg"
      working-directory: ${{ matrix.solution.name }}
