---
name: ci

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      nuget:
        type: boolean
        required: true
        default: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        fetch-depth: 1
        fetch-tags: true

    - name: Dotnet setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet nuget source
      run: >-
        dotnet nuget add source
        --name "github"
        --username "BeeHiveJava"
        --password "${{ secrets.GITHUB_TOKEN }}"
        --store-password-in-clear-text
        "https://nuget.pkg.github.com/BeeHiveJava/index.json"
      working-directory: ${{ inputs.name }}

    - name: Dotnet restore
      run: dotnet restore
      working-directory: ${{ inputs.name }}

    - name: Dotnet build
      run: dotnet build --no-restore --configuration "Release"
      working-directory: ${{ inputs.name }}

    - name: Dotnet test
      run: dotnet test --no-build --configuration "Release"
      working-directory: ${{ inputs.name }}

    - name: Get commit sha
      run: |-
        if [ "${{ github.ref_name }}" != releases/v* ]; then
          echo "value=`echo ${{ github.sha }} | cut -c1-8`" >> "$GITHUB_OUTPUT"
        else
          echo "value=" >> "$GITHUB_OUTPUT"
        fi
      id: sha
      if: ${{ inputs.nuget }}

    - name: Dotnet pack
      run: dotnet pack --no-build --configuration "Release" --version-suffix "pre.${{ steps.sha.outputs.value }}"
      working-directory: ${{ inputs.name }}
      if: ${{ inputs.nuget }}

    - name: Dotnet push
      run: >-
        dotnet nuget push
        --source "github"
        --api-key "${{ secrets.GITHUB_TOKEN }}"
        "**/*.nupkg"
      working-directory: ${{ inputs.name }}
      if: ${{ inputs.nuget }}
